let a= "BGROGHERWIUFHIUEWIF BEBFIEBWI BIEBFIULBWEIF FBVWEEFIEWG FBWEBFIUEWUWE WEFBFUWEUFBEW  HFWEFBVWEUBFILWE WBJ FWIHFYUEFFE WEVVEWVH  QGJ HVIVEWI FEGF EIHBVFIULWVEF WHBVIULBFVEW  FWEVIVWEIY W  UV  G BVIVBV  W BVWEHL   HEHBIHLRBBVHJ W WEV FBVWEF WB FWV WF K"
console.log(a.length)
console.log(a.toUpperCase())
console.log(a.toLowerCase())